# -*- coding: utf-8 -*-
"""[W3]_14888.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wMvr6tNZMha75wDrBgwCHSwBLCyOZI2w
"""

# W3 14888 연산자 끼워넣기

def dfs(cnt, ans):
    global maxnum, minnum

    if cnt == N-1:
        maxnum = max(ans, maxnum)
        minnum = min(ans, minnum)
        return

    if op[0] != 0 : # 덧셈
        op[0] -= 1
        dfs(cnt+1, ans + nums[cnt+1])
        op[0] += 1

    if op[1] != 0 : # 뺄셈
        op[1]-= 1
        dfs(cnt+1, ans - nums[cnt+1])
        op[1] += 1

    if op[2] != 0 : # 곱셈
        op[2] -= 1
        dfs(cnt+1, ans * nums[cnt+1])
        op[2] += 1

    if op[3] != 0 : #나눗셈
        op[3] -= 1
        dfs(cnt+1, int(ans/nums[cnt+1]))
        op[3] += 1


## __main__ ##
maxnum = -(10)**9
minnum = 10**9
N = int(input())
nums = list(map(int, input().split()))
op = list(map(int, input().split()))

dfs(0, nums[0])

print(maxnum)
print(minnum)