# -*- coding: utf-8 -*-
"""[W3]_14889.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E-dUXHiLiKbtRnU2VhHmaD0zESkg5wWH
"""

# W3 14889 스타트와 링크

def dfs(cnt, idx):
    global result
    if cnt == N//2:
        A = 0
        B = 0
        for i in range(N):
            for j in range(N):
                if visited[i] and visited[j]:
                    A += link[i][j]
                elif not visited[i] and not visited[j]:
                    B += link[i][j]
        result = min(result, abs(A-B))
        return

    for i in range(idx,N):
        if not visited[i]:
            visited[i] = True
            dfs(cnt+1,i+1)
            visited[i] = False


## __main__ ##
N = int(input())
link = [list(map(int, input().split())) for _ in range(N)]
visited = [False for _ in range(N)]

result = 1000000
dfs(0, 0)
print(result)