# -*- coding: utf-8 -*-
"""[W3]_1339.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cRxbw9MBL1aPo8rEi-wIWMr893T296tV
"""

# W3 1339 단어수학

N = int(input())
alphabet = [0 for _ in range(26)]

for _ in range(N):
    word = list(input().rstrip())
    for i in range(len(word)):
        alphabet[ord(word[i])-ord('A')] += 10 ** (len(word)-1-i)

alphabet.sort(reverse=True)
ans = 0
num = 9

for i in range(len(alphabet)):
    if alphabet[i] == 0:
        break
    ans += alphabet[i] * num
    num -= 1

print(ans)