# -*- coding: utf-8 -*-
"""[W3]_16929.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mS44B3KgOZCj89P8d4fYFWbrV4cFaJ-c
"""

# W3 16929 Two Dots

def dfs(color, x, y, cnt):
    global flag
    if flag:  # 이미 서클이 완성되었으면 종료
        return

    for i in range(4):
        nx, ny = x + dx[i], y + dy[i]  # 이동
        if nx < 0 or ny < 0 or nx >= M or ny >= N:  # 범위 벗어나면 pass
            continue
        if cnt >= 4 and nx == start_x and ny == start_y:  # 서클 완성되면 Yes
            flag = True
            print("Yes")
            exit()
        if board[ny][nx] == color and visited[ny][nx] == False:  # 색이 같고 방문을 안했다면 재귀
            visited[ny][nx] = True
            dfs(board[ny][nx], nx, ny, cnt+1)
            visited[ny][nx] = False


## __main__ ##
N, M = map(int, input().split())
board = [list(input().rstrip()) for _ in range(N)]

visited = [[False]*M for _ in range(N)]
# 남, 동, 북, 서
dx = [0, 1, 0, -1]
dy = [1, 0, -1, 0]
flag = False

for row in range(N):
    for col in range(M):
        visited[row][col] = True
        start_x, start_y = col, row
        dfs(board[row][col], col, row, 1)
        visited[row][col] = False

print("No")