# -*- coding: utf-8 -*-
"""[W5]_11728.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k8Yw5a1JNN831rZcxOI6gi-LI441dz8T
"""

# W5 11728 배열 합치기

N, M = map(int, input().split())
A = list(map(int, input().split()))
B = list(map(int, input().split()))

result = A + B
result.sort()
result = ' '.join(map(str, result))
print(result)