# -*- coding: utf-8 -*-
"""[W5]_1011.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11SeR08OGveVuaU1pyW-HtrNnOHbicbhj
"""

# W5 1011 Fly me to the Alpha Centauri

T = int(input())

for _ in range(T):
    x, y = map(int, input().split())

    distance = y - x # y와 x사이의 거리
    tmp = 0 # 이동 거리
    cnt = 0 # 공간 장치 이동 횟수
    moving = 0 # 반복 횟수

    while tmp < distance:
        cnt += 1
        if cnt % 2 != 0:
            moving += 1
        tmp += moving
    print(cnt)